#!/bin/sh
# Script to create a PyQT deb package using fpm
#
# This script will create a folder structure that will be used as input
# for the fpm command and copy into it all the distributable files generated by
# pyinstaller.
#
# We will create a folder with the same structure Linux systems expects:
#  - /opt for our executable and associated files (a.k.a our dist/ folder)
#  - /usr/share/applications (for the .desktop file)
#  - /usr/share/icons/hicolor/scalable/apps for our svg icons (only svg in scalable folder)
#
# More info:
#  - https://www.pythonguis.com/tutorials/packaging-pyqt5-applications-linux-pyinstaller/
#  - https://fpm.readthedocs.io/en/latest/packages/dir.html#dir-local-files
#
# Create temporary folders
[ -e tmp ] && rm -r tmp
mkdir -p tmp/opt
mkdir -p tmp/usr/share/applications
mkdir -p tmp/usr/share/icons/hicolor/scalable/apps

# Build the project
[ -e markdownwiki.dist ] && rm -r markdownwiki.dist
uv run pyside6-deploy -c pysidedeploy.spec

# Copy files
cp -r dist/markdownwiki.dist tmp/opt/markdownwiki
cp ./packaging/linux/icon.svg tmp/usr/share/icons/hicolor/scalable/apps/me.pdelboca.markdownwiki.svg
cp ./packaging/linux/markdownwiki.desktop tmp/usr/share/applications

# Change permissions
# Packages retain the permissions of installed files from when they were packaged,
# but will be installed by root. In order for ordinary users to be able to run the
# application, we need to change the permissions.
find tmp/opt/markdownwiki -type f -exec chmod 644 -- {} +
find tmp/opt/markdownwiki -type d -exec chmod 755 -- {} +
find tmp/usr/share -type f -exec chmod 644 -- {} +
chmod +x tmp/opt/markdownwiki/main.bin

# Create the deb package
VERSION=$(uv version --short)
FILENAME=markdownwiki-linux-$VERSION.deb
[ -e dist/$FILENAME ] && rm dist/$FILENAME
fpm -C tmp -s dir -t deb -n "markdownwiki" -v $VERSION  -p dist/$FILENAME
