[project]
name = "markdown-wiki"
version = "0.0.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "markdown>=3.8",
    "pyside6==6.9.0",
    "ruff>=0.11.10",
]

[dependency-groups]
dev = [
    "ipdb>=0.13.13",
]
