name: Release

on:
  push:
    tags:
      - v*.*.*

jobs:
  linux-release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.4"
      - name: Install OS Dependencies
        run: |
          sudo apt-get update
          sudo gem install fpm
          fpm --version
      - name: Install Qt Dependencies
        run: |
          # https://forum.qt.io/post/769050
          sudo apt-get install libxcb-icccm4 libxcb-image0-dev libxcb-keysyms1 libxcb-render-util0 libxcb-xkb1 libxcb-xinerama0 libxkbcommon-x11-0 libxcb-cursor0 libxcb-shape0-dev
      - name: Install Dependencies
        run: |
          uv sync
      - name: Build the deb package
        run: |
          chmod +x create-deb.sh
          ./create-deb.sh
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/markdownwiki-linux.deb
          draft: true
          overwrite_files: false
